# Generated by Django 5.0.3 on 2024-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prod_app', models.TextField(default='')),
                ('category', models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-cream'), ('LS', 'Lassi'), ('BT', 'Butter')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
