# Generated by Django 5.0.3 on 2024-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-cream'), ('LS', 'Lassi'), ('BT', 'Butter'), ('CM', 'Cream'), ('CA', 'Cream'), ('CH', 'Chocklate')], max_length=2),
        ),
    ]
