# Generated by Django 5.0.3 on 2024-05-23 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.ImageField(default=0, upload_to='')),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('MP', 'MP'), ('Goa', 'Goa'), ('Manipur', 'Manipur'), ('Bihar', 'Bihar'), ('Bihar', 'Bihar'), ('Up', 'Up'), ('Kerala', 'Kerala'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Nagaland', 'Nagaland')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
