# Generated by Django 5.0.3 on 2024-06-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_app',
            new_name='prodapp',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
